name: Deploy to Ubuntu VPS

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            bash -l -c '
              set -e

              export PNPM_HOME="$HOME/.local/share/pnpm"
              export PATH="$PNPM_HOME:$PATH"

              cd ${{ secrets.APP_PATH }}

              git pull origin main
              pnpm install
              pnpm build
              cp .env dist/.env

              if pm2 describe patrol-be > /dev/null; then
                pm2 restart patrol-be --update-env
              else
                pm2 start pnpm --name "patrol-be" -- start
              fi

              pm2 save
            '
