name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            cd ${{ secrets.APP_PATH }}
            git pull origin main

            if ! command -v pnpm &> /dev/null; then
              echo "Installing pnpm..."
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PATH="$HOME/.local/share/pnpm:$PATH"
            fi

            pnpm install
            pnpm build

            cp .env dist/.env

            pm2 restart ${{ secrets.APP_ID }} || pm2 start dist/index.js --name "${{ secrets.APP_ID }}"
